### ISSUE TITLE
tabs overlap problem

### ISSUE THREAD

**Issue by gorkemozdogan** [aarondo/tabulous.js#18]
Hello , 
such a great script. thank you for the plugin. i realized some problem which is related tab containers. i added some elements on  label textbox dropdown etc and try to click them.It doesnt work  than i digged to html with firebug and  i saw tab2 overlap to tab1.so because control event didn't trigger.

i guess this is problem due to css class: hidescale  property :  opacity property.

**Comment by theahall** [comment]
Likewise...any solution? The next post about changing scale doesn't work.

**Comment by aarondo** [comment]
I've rollbacked the commit. The demo version should work now :-)
