### ISSUE TITLE
Current demo doesnt work

### ISSUE THREAD

**Issue by tr3intaydos** [aarondo/tabulous.js#20]
The demo in the repo doesnt work, my guess is that you forgot update the html in the demo after one commit adding "target_class" stuff, the demo in [here](http://git.aaronlumsden.com/tabulous.js/) uses a previous version, and that one works.

**Comment by lext-7** [comment]
the same as the former

**Comment by lext-7** [comment]
https://github.com/aarondo/tabulous.js/issues/20 @tr3intaydos

**Comment by aarondo** [comment]
I've rolled back to the working version now. The demo should work. Sorry for the inconvenience
